/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const AssetAllocation = IDL.Record({
  'share' : IDL.Nat,
  'beneficiaryId' : IDL.Nat,
});
export const Asset = IDL.Record({
  'id' : IDL.Nat,
  'decimals' : IDL.Nat,
  'balance' : IDL.Nat,
  'name' : IDL.Text,
  'allocations' : IDL.Vec(AssetAllocation),
  'symbol' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Beneficiary = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'allocationShare' : IDL.Nat,
  'walletAddress' : IDL.Text,
});
export const AuditEvent = IDL.Record({
  'id' : IDL.Nat,
  'prevHash' : IDL.Vec(IDL.Nat8),
  'hash' : IDL.Vec(IDL.Nat8),
  'description' : IDL.Text,
  'timestamp' : Timestamp,
  'eventType' : IDL.Text,
});
export const SwitchStatus = IDL.Variant({
  'armed' : IDL.Null,
  'disarmed' : IDL.Null,
});
export const SwitchState = IDL.Record({
  'status' : SwitchStatus,
  'cadenceSeconds' : IDL.Nat,
  'armedAt' : IDL.Opt(Timestamp),
  'lastCheckIn' : IDL.Opt(Timestamp),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const SwitchTimeline = IDL.Record({
  'status' : SwitchStatus,
  'cadenceSeconds' : IDL.Nat,
  'timeSinceLastCheckIn' : IDL.Opt(IDL.Nat),
  'timeUntilRelease' : IDL.Opt(IDL.Nat),
});
export const WalletBalance = IDL.Record({
  'assets' : IDL.Vec(Asset),
  'totalUsd' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addAsset' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(AssetAllocation)],
      [Asset],
      [],
    ),
  'addBeneficiary' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Beneficiary], []),
  'appendAuditEvent' : IDL.Func([IDL.Text, IDL.Text], [AuditEvent], []),
  'armSwitch' : IDL.Func([IDL.Nat], [SwitchState], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkIn' : IDL.Func([], [SwitchState], []),
  'disarmSwitch' : IDL.Func([], [SwitchState], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSwitchState' : IDL.Func([], [SwitchState], ['query']),
  'getSwitchTimeline' : IDL.Func([], [SwitchTimeline], ['query']),
  'getWalletBalance' : IDL.Func([], [WalletBalance], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
  'listAuditEvents' : IDL.Func([], [IDL.Vec(AuditEvent)], ['query']),
  'listBeneficiaries' : IDL.Func([], [IDL.Vec(Beneficiary)], ['query']),
  'removeBeneficiary' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateBeneficiary' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Opt(Beneficiary)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const AssetAllocation = IDL.Record({
    'share' : IDL.Nat,
    'beneficiaryId' : IDL.Nat,
  });
  const Asset = IDL.Record({
    'id' : IDL.Nat,
    'decimals' : IDL.Nat,
    'balance' : IDL.Nat,
    'name' : IDL.Text,
    'allocations' : IDL.Vec(AssetAllocation),
    'symbol' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Beneficiary = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'allocationShare' : IDL.Nat,
    'walletAddress' : IDL.Text,
  });
  const AuditEvent = IDL.Record({
    'id' : IDL.Nat,
    'prevHash' : IDL.Vec(IDL.Nat8),
    'hash' : IDL.Vec(IDL.Nat8),
    'description' : IDL.Text,
    'timestamp' : Timestamp,
    'eventType' : IDL.Text,
  });
  const SwitchStatus = IDL.Variant({
    'armed' : IDL.Null,
    'disarmed' : IDL.Null,
  });
  const SwitchState = IDL.Record({
    'status' : SwitchStatus,
    'cadenceSeconds' : IDL.Nat,
    'armedAt' : IDL.Opt(Timestamp),
    'lastCheckIn' : IDL.Opt(Timestamp),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const SwitchTimeline = IDL.Record({
    'status' : SwitchStatus,
    'cadenceSeconds' : IDL.Nat,
    'timeSinceLastCheckIn' : IDL.Opt(IDL.Nat),
    'timeUntilRelease' : IDL.Opt(IDL.Nat),
  });
  const WalletBalance = IDL.Record({
    'assets' : IDL.Vec(Asset),
    'totalUsd' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addAsset' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(AssetAllocation)],
        [Asset],
        [],
      ),
    'addBeneficiary' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [Beneficiary],
        [],
      ),
    'appendAuditEvent' : IDL.Func([IDL.Text, IDL.Text], [AuditEvent], []),
    'armSwitch' : IDL.Func([IDL.Nat], [SwitchState], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkIn' : IDL.Func([], [SwitchState], []),
    'disarmSwitch' : IDL.Func([], [SwitchState], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSwitchState' : IDL.Func([], [SwitchState], ['query']),
    'getSwitchTimeline' : IDL.Func([], [SwitchTimeline], ['query']),
    'getWalletBalance' : IDL.Func([], [WalletBalance], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
    'listAuditEvents' : IDL.Func([], [IDL.Vec(AuditEvent)], ['query']),
    'listBeneficiaries' : IDL.Func([], [IDL.Vec(Beneficiary)], ['query']),
    'removeBeneficiary' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateBeneficiary' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Opt(Beneficiary)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };