/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Asset {
  'id' : bigint,
  'decimals' : bigint,
  'balance' : bigint,
  'name' : string,
  'allocations' : Array<AssetAllocation>,
  'symbol' : string,
}
export interface AssetAllocation { 'share' : bigint, 'beneficiaryId' : bigint }
export interface AuditEvent {
  'id' : bigint,
  'prevHash' : Uint8Array,
  'hash' : Uint8Array,
  'description' : string,
  'timestamp' : Timestamp,
  'eventType' : string,
}
export interface Beneficiary {
  'id' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'allocationShare' : bigint,
  'walletAddress' : string,
}
export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface SwitchState {
  'status' : SwitchStatus,
  'cadenceSeconds' : bigint,
  'armedAt' : [] | [Timestamp],
  'lastCheckIn' : [] | [Timestamp],
}
export type SwitchStatus = { 'armed' : null } |
  { 'disarmed' : null };
export interface SwitchTimeline {
  'status' : SwitchStatus,
  'cadenceSeconds' : bigint,
  'timeSinceLastCheckIn' : [] | [bigint],
  'timeUntilRelease' : [] | [bigint],
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface WalletBalance {
  'assets' : Array<Asset>,
  'totalUsd' : [] | [bigint],
}
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addAsset' : ActorMethod<
    [string, string, bigint, bigint, Array<AssetAllocation>],
    Asset
  >,
  'addBeneficiary' : ActorMethod<[string, bigint, string], Beneficiary>,
  'appendAuditEvent' : ActorMethod<[string, string], AuditEvent>,
  'armSwitch' : ActorMethod<[bigint], SwitchState>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkIn' : ActorMethod<[], SwitchState>,
  'disarmSwitch' : ActorMethod<[], SwitchState>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSwitchState' : ActorMethod<[], SwitchState>,
  'getSwitchTimeline' : ActorMethod<[], SwitchTimeline>,
  'getWalletBalance' : ActorMethod<[], WalletBalance>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAssets' : ActorMethod<[], Array<Asset>>,
  'listAuditEvents' : ActorMethod<[], Array<AuditEvent>>,
  'listBeneficiaries' : ActorMethod<[], Array<Beneficiary>>,
  'removeBeneficiary' : ActorMethod<[bigint], boolean>,
  'schema' : ActorMethod<[], string>,
  'updateBeneficiary' : ActorMethod<
    [bigint, string, bigint, string],
    [] | [Beneficiary]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];